# Generated by Django 4.2.4 on 2023-08-24 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
                ('social1', models.CharField(max_length=100)),
                ('social2', models.CharField(max_length=100)),
                ('social3', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/Members/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/About/'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/Announcement/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/Event/'),
        ),
        migrations.AlterField(
            model_name='home1',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/Home1/'),
        ),
        migrations.AlterField(
            model_name='home2',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/Home2/'),
        ),
        migrations.AlterField(
            model_name='home3',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/Home3/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/Post/'),
        ),
    ]
