# Generated by Django 4.2.4 on 2023-08-24 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_member_event_category_alter_about_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='about_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
