# Generated by Django 4.2.4 on 2023-08-24 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_about_about_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/Member/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='social1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='social2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='social3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
