# Generated by Django 4.2.2 on 2024-01-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='social1',
            new_name='facebook',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='social2',
            new_name='insta',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='social3',
            new_name='linkedin',
        ),
        migrations.AddField(
            model_name='member',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='member',
            name='year',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
