# Generated by Django 4.2.2 on 2024-02-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_delete_archivebanners_member_order_member_pronouns'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail_url', models.URLField()),
                ('caption', models.TextField()),
            ],
        ),
    ]
