# Generated by Django 4.2.2 on 2024-02-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_instagrampost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrampost',
            name='thumbnail_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
