# Generated by Django 4.2.2 on 2024-02-09 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_alter_instagrampost_thumbnail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrampost',
            name='thumbnail_url',
            field=models.URLField(blank=True, default='', max_length=5000),
        ),
    ]
